

name: MCPServer CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.vscode/*.json'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.vscode/*.json'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore MCPServer.sln
      - name: Build
        run: dotnet build MCPServer.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test MCPServer.sln --no-build --verbosity normal
