name: React Client Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'react/**'
      - '.github/workflows/react-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'react/**'
      - '.github/workflows/react-tests.yml'

jobs:
  test:
    name: React Client Testing
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./react
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './react/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint
        
      - name: Build React app
        run: npm run build
        
      - name: Run tests
        run: npm test -- --passWithNoTests --watchAll=false
        
      - name: Run tests with coverage
        run: npm run test:coverage -- --watchAll=false
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: react-test-results-node-${{ matrix.node-version }}
          path: |
            react/coverage/
            react/junit.xml
            react/dist/
          
      - name: Upload coverage to Codecov (Node 20.x only)
        if: matrix.node-version == '20.x'
        uses: codecov/codecov-action@v4
        with:
          file: ./react/coverage/lcov.info
          flags: react
          name: react-coverage
          fail_ci_if_error: false