name: TypeScript Server Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'typescript/**'
      - '.github/workflows/typescript-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'typescript/**'
      - '.github/workflows/typescript-tests.yml'

jobs:
  test:
    name: TypeScript Server Testing
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./typescript
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './typescript/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build TypeScript
        run: npm run build
        
      - name: Run tests
        run: npm test
        
      - name: Run tests with coverage
        run: npm run test:coverage
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: typescript-test-results-node-${{ matrix.node-version }}
          path: |
            typescript/coverage/
            typescript/junit.xml
          
      - name: Upload coverage to Codecov (Node 20.x only)
        if: matrix.node-version == '20.x'
        uses: codecov/codecov-action@v4
        with:
          file: ./typescript/coverage/lcov.info
          flags: typescript
          name: typescript-coverage
          fail_ci_if_error: false